In [1]:
import itertools
import re
import pandas as pd
import numpy as np
import os 

from script_get_de_and_summary_jupyter import *

In [2]:
os.chdir("/hdd_14T/data/PXD002952/osw_res_20210303/hye124/ttof5600/32fix")
hye124_ttof5600_32fix, hye124_ttof5600_32fix_de = get_summary_hye124()

/home/ptruong/git/dia_sum/scripts/PXD002952/script_get_de_and_summary_jupyter.py:285: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_sample["proteinQuantity"] = df_sample["ProteinName"].map(get_protein_quantity)

time: 21.54874062538147 s
time: 23.581368923187256 s
time: 21.134708404541016 s
time: 20.038915872573853 s

/home/ptruong/git/dia_sum/scripts/PXD002952/script_get_de_and_summary_jupyter.py:353: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  df_xs = pd.concat(df_x_list, axis = 1)

In [3]:
hye124_ttof5600_32fix

  experiment_id sample_id proteins peptides
0     001-Pedro       [1]     1600    11992
1     002-Pedro       [2]     1690    12932
2     003-Pedro       [1]     1594    11877
3     005-Pedro       [1]     1555    11426

In [4]:
hye124_ttof5600_32fix_de

,human_de,ecoli_de,yeast_de
"(001-Pedro_1_proteinQuantity, 002-Pedro_2_proteinQuantity)",399,1,0
"(001-Pedro_1_proteinQuantity, 003-Pedro_1_proteinQuantity)",481,0,0
"(001-Pedro_1_proteinQuantity, 005-Pedro_1_proteinQuantity)",414,0,0
"(002-Pedro_2_proteinQuantity, 003-Pedro_1_proteinQuantity)",408,0,12
"(002-Pedro_2_proteinQuantity, 005-Pedro_1_proteinQuantity)",387,0,12
"(003-Pedro_1_proteinQuantity, 005-Pedro_1_proteinQuantity)",419,0,0

In [5]:
os.chdir("/hdd_14T/data/PXD002952/osw_res_20210303/hye124/ttof5600/32fix_w_64v_library_test")
hye124_ttof5600_32fix_w_64var_specLib, hye124_ttof5600_32fix_w_64var_specLib_de = get_summary_hye124()

time: 20.936028718948364 s
time: 24.134610176086426 s
time: 21.143524885177612 s
time: 20.38842463493347 s

In [6]:
hye124_ttof5600_32fix_w_64var_specLib

  experiment_id sample_id proteins peptides
0     001-Pedro       [1]     1855    10653
1     002-Pedro       [2]     2013    11719
2     003-Pedro       [1]     1871    10591
3     005-Pedro       [1]     1797    10073

In [7]:
hye124_ttof5600_32fix_w_64var_specLib_de

,human_de,ecoli_de,yeast_de
"(001-Pedro_1_proteinQuantity, 002-Pedro_2_proteinQuantity)",143,0,8
"(001-Pedro_1_proteinQuantity, 003-Pedro_1_proteinQuantity)",331,0,0
"(001-Pedro_1_proteinQuantity, 005-Pedro_1_proteinQuantity)",290,0,1
"(002-Pedro_2_proteinQuantity, 003-Pedro_1_proteinQuantity)",158,0,4
"(002-Pedro_2_proteinQuantity, 005-Pedro_1_proteinQuantity)",141,0,3
"(003-Pedro_1_proteinQuantity, 005-Pedro_1_proteinQuantity)",288,0,3

In [8]:
os.chdir("/hdd_14T/data/PXD002952/osw_res_20210303/hye124/ttof5600/64var")
hye124_ttof5600_64var, hye124_ttof5600_64var_de = get_summary_hye124()

time: 43.671239376068115 s
time: 37.32342290878296 s
time: 42.48905324935913 s
time: 41.44592523574829 s

In [9]:
hye124_ttof5600_64var

  experiment_id sample_id proteins peptides
0     007-Pedro       [1]     2411    20071
1     008-Pedro       [2]     2207    17671
2     009-Pedro       [1]     2331    19232
3     010-Pedro       [2]     2374    19232

In [10]:
hye124_ttof5600_64var_de

,human_de,ecoli_de,yeast_de
"(007-Pedro_1_proteinQuantity, 008-Pedro_2_proteinQuantity)",230,0,0
"(007-Pedro_1_proteinQuantity, 009-Pedro_1_proteinQuantity)",569,0,1
"(007-Pedro_1_proteinQuantity, 010-Pedro_2_proteinQuantity)",472,0,0
"(008-Pedro_2_proteinQuantity, 009-Pedro_1_proteinQuantity)",380,0,96
"(008-Pedro_2_proteinQuantity, 010-Pedro_2_proteinQuantity)",337,0,0
"(009-Pedro_1_proteinQuantity, 010-Pedro_2_proteinQuantity)",530,0,1

In [11]:
os.chdir("/hdd_14T/data/PXD002952/osw_res_20210303/hye124/ttof6600/32fix")
hye124_ttof6600_32fix, hye124_ttof6600_32fix_de = get_summary_hye124()

time: 55.06310415267944 s
time: 57.07259678840637 s
time: 55.17685508728027 s
time: 60.63970923423767 s
time: 53.74865508079529 s
time: 65.17827153205872 s

In [12]:
hye124_ttof6600_32fix

  experiment_id sample_id proteins peptides
0     002-Pedro       [-]     2758    24194
1     003-Pedro       [-]     2838    25215
2     004-Pedro       [-]     2739    23746
3     005-Pedro       [-]     2890    25820
4     006-Pedro       [-]     2753    24102
5     007-Pedro       [-]     2892    25524

In [13]:
hye124_ttof6600_32fix_de

,human_de,ecoli_de,yeast_de
"(002-Pedro_-_proteinQuantity, 003-Pedro_-_proteinQuantity)",654,0,1
"(002-Pedro_-_proteinQuantity, 004-Pedro_-_proteinQuantity)",220,0,0
"(002-Pedro_-_proteinQuantity, 005-Pedro_-_proteinQuantity)",366,0,0
"(002-Pedro_-_proteinQuantity, 006-Pedro_-_proteinQuantity)",186,0,2
"(002-Pedro_-_proteinQuantity, 007-Pedro_-_proteinQuantity)",248,0,1
"(003-Pedro_-_proteinQuantity, 004-Pedro_-_proteinQuantity)",384,0,49
"(003-Pedro_-_proteinQuantity, 005-Pedro_-_proteinQuantity)",581,0,1
"(003-Pedro_-_proteinQuantity, 006-Pedro_-_proteinQuantity)",277,1,77
"(003-Pedro_-_proteinQuantity, 007-Pedro_-_proteinQuantity)",387,0,4
"(004-Pedro_-_proteinQuantity, 005-Pedro_-_proteinQuantity)",666,0,0
"(004-Pedro_-_proteinQuantity, 006-Pedro_-_proteinQuantity)",700,0,2
"(004-Pedro_-_proteinQuantity, 007-Pedro_-_proteinQuantity)",643,0,0
"(005-Pedro_-_proteinQuantity, 006-Pedro_-_proteinQuantity)",501,1,55
"(005-Pedro_-_proteinQuantity, 007-Pedro_-_proteinQuantity)",685,0,3
"(006-Pedro_-_proteinQuantity, 007-Pedro_-_proteinQuantity)",597,0,0

In [14]:
os.chdir("/hdd_14T/data/PXD002952/osw_res_20210303/hye110/ttof6600/32fix")
hye110_ttof6600_32fix, hye110_ttof6600_32fix_de = get_summary_hye110()

/home/ptruong/git/dia_sum/scripts/PXD002952/script_get_de_and_summary_jupyter.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_sample["proteinQuantity"] = df_sample["ProteinName"].map(get_protein_quantity)

time: 28.873619556427002 s
time: 31.177311658859253 s
time: 27.822954177856445 s
time: 31.1245174407959 s
time: 27.26920247077942 s

/home/ptruong/git/dia_sum/scripts/PXD002952/script_get_de_and_summary_jupyter.py:110: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  df_xs = pd.concat(df_x_list, axis = 1)

In [15]:
hye110_ttof6600_32fix

  experiment_id sample_id proteins peptides
0     001-Pedro       [A]     1844    14612
1     002-Pedro       [B]     1857    15650
2     003-Pedro       [A]     1804    14310
3     004-Pedro       [B]     1850    15495
4     010-Pedro       [A]     1756    13650

In [16]:
hye110_ttof6600_32fix_de

,human_de,ecoli_de,yeast_de
"(001-Pedro_A_proteinQuantity, 002-Pedro_B_proteinQuantity)",408,69,95
"(001-Pedro_A_proteinQuantity, 003-Pedro_A_proteinQuantity)",353,0,0
"(001-Pedro_A_proteinQuantity, 004-Pedro_B_proteinQuantity)",395,71,101
"(001-Pedro_A_proteinQuantity, 010-Pedro_A_proteinQuantity)",46,0,1
"(002-Pedro_B_proteinQuantity, 003-Pedro_A_proteinQuantity)",210,102,94
"(002-Pedro_B_proteinQuantity, 004-Pedro_B_proteinQuantity)",632,0,0
"(002-Pedro_B_proteinQuantity, 010-Pedro_A_proteinQuantity)",40,114,92
"(003-Pedro_A_proteinQuantity, 004-Pedro_B_proteinQuantity)",193,111,99
"(003-Pedro_A_proteinQuantity, 010-Pedro_A_proteinQuantity)",187,0,0
"(004-Pedro_B_proteinQuantity, 010-Pedro_A_proteinQuantity)",41,110,98

In [17]:
os.chdir("/hdd_14T/data/PXD002952/osw_res_20210303/hye110/ttof6600/32var")
hye110_ttof6600_32var, hye110_ttof6600_32var_de = get_summary_hye110()

time: 35.07282996177673 s
time: 38.1522274017334 s
time: 33.766634702682495 s
time: 34.519585609436035 s
time: 33.616631746292114 s
time: 35.151132345199585 s

In [18]:
hye110_ttof6600_32var

  experiment_id sample_id proteins peptides
0     001-Pedro  [A.mzML]     2167    17297
1     002-Pedro  [B.mzML]     2176    18273
2     003-Pedro  [A.mzML]     2124    17033
3     004-Pedro  [B.mzML]     2091    17222
4     005-Pedro  [A.mzML]     2132    16955
5     006-Pedro  [B.mzML]     2094    17582

In [19]:
hye110_ttof6600_32var_de

,human_de,ecoli_de,yeast_de
"(001-Pedro_A.mzML_proteinQuantity, 002-Pedro_B.mzML_proteinQuantity)",366,0,0
"(001-Pedro_A.mzML_proteinQuantity, 003-Pedro_A.mzML_proteinQuantity)",788,0,0
"(001-Pedro_A.mzML_proteinQuantity, 004-Pedro_B.mzML_proteinQuantity)",503,0,0
"(001-Pedro_A.mzML_proteinQuantity, 005-Pedro_A.mzML_proteinQuantity)",703,0,0
"(001-Pedro_A.mzML_proteinQuantity, 006-Pedro_B.mzML_proteinQuantity)",543,0,0
"(002-Pedro_B.mzML_proteinQuantity, 003-Pedro_A.mzML_proteinQuantity)",302,125,159
"(002-Pedro_B.mzML_proteinQuantity, 004-Pedro_B.mzML_proteinQuantity)",539,0,0
"(002-Pedro_B.mzML_proteinQuantity, 005-Pedro_A.mzML_proteinQuantity)",252,144,158
"(002-Pedro_B.mzML_proteinQuantity, 006-Pedro_B.mzML_proteinQuantity)",539,0,0
"(003-Pedro_A.mzML_proteinQuantity, 004-Pedro_B.mzML_proteinQuantity)",459,0,0
"(003-Pedro_A.mzML_proteinQuantity, 005-Pedro_A.mzML_proteinQuantity)",740,0,1
"(003-Pedro_A.mzML_proteinQuantity, 006-Pedro_B.mzML_proteinQuantity)",519,0,0
"(004-Pedro_B.mzML_proteinQuantity, 005-Pedro_A.mzML_proteinQuantity)",403,121,143
"(004-Pedro_B.mzML_proteinQuantity, 006-Pedro_B.mzML_proteinQuantity)",748,0,0
"(005-Pedro_A.mzML_proteinQuantity, 006-Pedro_B.mzML_proteinQuantity)",432,0,0

In [20]:
os.chdir("/hdd_14T/data/PXD002952/osw_res_20210303/hye110/ttof6600/64fix")
hye110_ttof6600_64fix, hye110_ttof6600_64fix_de = get_summary_hye110()

time: 31.358431577682495 s
time: 33.35569381713867 s
time: 30.573335647583008 s
time: 33.49097418785095 s
time: 31.23229742050171 s
time: 34.52995800971985 s

In [21]:
hye110_ttof6600_64fix

  experiment_id sample_id proteins peptides
0     001-Pedro  [A.mzML]     2018    15947
1     002-Pedro  [B.mzML]     1997    16709
2     003-Pedro  [A.mzML]     1954    15267
3     004-Pedro  [B.mzML]     1956    16395
4     005-Pedro  [A.mzML]     2008    15839
5     006-Pedro  [B.mzML]     1955    16163

In [22]:
hye110_ttof6600_64fix_de

,human_de,ecoli_de,yeast_de
"(001-Pedro_A.mzML_proteinQuantity, 002-Pedro_B.mzML_proteinQuantity)",403,0,0
"(001-Pedro_A.mzML_proteinQuantity, 003-Pedro_A.mzML_proteinQuantity)",73,0,1
"(001-Pedro_A.mzML_proteinQuantity, 004-Pedro_B.mzML_proteinQuantity)",414,0,0
"(001-Pedro_A.mzML_proteinQuantity, 005-Pedro_A.mzML_proteinQuantity)",226,0,0
"(001-Pedro_A.mzML_proteinQuantity, 006-Pedro_B.mzML_proteinQuantity)",451,0,0
"(002-Pedro_B.mzML_proteinQuantity, 003-Pedro_A.mzML_proteinQuantity)",75,147,113
"(002-Pedro_B.mzML_proteinQuantity, 004-Pedro_B.mzML_proteinQuantity)",342,0,0
"(002-Pedro_B.mzML_proteinQuantity, 005-Pedro_A.mzML_proteinQuantity)",157,153,114
"(002-Pedro_B.mzML_proteinQuantity, 006-Pedro_B.mzML_proteinQuantity)",324,0,0
"(003-Pedro_A.mzML_proteinQuantity, 004-Pedro_B.mzML_proteinQuantity)",181,0,0
"(003-Pedro_A.mzML_proteinQuantity, 005-Pedro_A.mzML_proteinQuantity)",415,0,0
"(003-Pedro_A.mzML_proteinQuantity, 006-Pedro_B.mzML_proteinQuantity)",167,0,0
"(004-Pedro_B.mzML_proteinQuantity, 005-Pedro_A.mzML_proteinQuantity)",353,136,110
"(004-Pedro_B.mzML_proteinQuantity, 006-Pedro_B.mzML_proteinQuantity)",649,0,0
"(005-Pedro_A.mzML_proteinQuantity, 006-Pedro_B.mzML_proteinQuantity)",311,0,0

In [23]:
os.chdir("/hdd_14T/data/PXD002952/osw_res_20210303/hye110/ttof6600/64var")
hye110_ttof6600_64var, hye110_ttof6600_64var_de = get_summary_hye110()

time: 45.911760330200195 s
time: 45.010289669036865 s
time: 45.63397765159607 s
time: 46.041316509246826 s
time: 44.12265467643738 s
time: 41.73828864097595 s

In [24]:
hye110_ttof6600_64var

  experiment_id sample_id proteins peptides
0     001-Pedro       [A]     2531    21548
1     002-Pedro       [B]     2385    20925
2     003-Pedro       [A]     2550    21542
3     004-Pedro       [B]     2431    21528
4     005-Pedro       [A]     2465    20839
5     006-Pedro       [B]     2294    19629

In [25]:
hye110_ttof6600_64var_de

,human_de,ecoli_de,yeast_de
"(001-Pedro_A_proteinQuantity, 002-Pedro_B_proteinQuantity)",555,125,195
"(001-Pedro_A_proteinQuantity, 003-Pedro_A_proteinQuantity)",892,0,0
"(001-Pedro_A_proteinQuantity, 004-Pedro_B_proteinQuantity)",649,122,214
"(001-Pedro_A_proteinQuantity, 005-Pedro_A_proteinQuantity)",570,0,0
"(001-Pedro_A_proteinQuantity, 006-Pedro_B_proteinQuantity)",432,89,181
"(002-Pedro_B_proteinQuantity, 003-Pedro_A_proteinQuantity)",641,140,195
"(002-Pedro_B_proteinQuantity, 004-Pedro_B_proteinQuantity)",858,0,2
"(002-Pedro_B_proteinQuantity, 005-Pedro_A_proteinQuantity)",549,161,195
"(002-Pedro_B_proteinQuantity, 006-Pedro_B_proteinQuantity)",573,0,2
"(003-Pedro_A_proteinQuantity, 004-Pedro_B_proteinQuantity)",679,136,214
"(003-Pedro_A_proteinQuantity, 005-Pedro_A_proteinQuantity)",650,0,0
"(003-Pedro_A_proteinQuantity, 006-Pedro_B_proteinQuantity)",461,85,181
"(004-Pedro_B_proteinQuantity, 005-Pedro_A_proteinQuantity)",612,162,214
"(004-Pedro_B_proteinQuantity, 006-Pedro_B_proteinQuantity)",622,0,0
"(005-Pedro_A_proteinQuantity, 006-Pedro_B_proteinQuantity)",588,122,181